### ISSUE TITLE
Can't display data from a specially prepared table

### ISSUE THREAD

**Issue by culebron** [suhora/clickhouse_connector#4]
We created a table with Point data type and timestamp. And somehow the plugin fails to load this, complaining that it can't display data matching the criteria. What criteria? I've not set any filter.

When I tried to enter anything in the basic query field, it showed error window with no content, then QGIS froze and crashed. (QGIS v3.28.10) The "No data available" window also ends in QGIS silently vanishing.

Any advice how to debug and maybe fix this myself, is welcome. (I code in Python for > decade.)

The issue:
![Selection_010](https://github.com/user-attachments/assets/f48435aa-be60-4fdf-af09-05b9df66ec0d)

The columns in DBeaver: (it's unaware of Point type)
![Selection_011](https://github.com/user-attachments/assets/837ae820-8124-4f6f-b3bc-fe106482a45c)

These columns in the table structure:
![Selection_012](https://github.com/user-attachments/assets/bb73c0d4-045c-47ae-b8e6-b1f8d828bf0e)

**Comment by lokeshsk** [comment]
Hi @culebron ,
First of all, thank you for trying out our plugin.
However,
As mentioned in README.md
By default:
If timestamp field is there in clickhouse table then last 8 hours data will be displayed (without any query), to query data beyond that use query tool to write your own queries.

Could you please verify if the timestamp filed in your case its **creation_date**, has recent data i.e with in 8 hour window of querying (current time).
If not write a custom query for it.

**Comment by culebron** [comment]
Hi,
I had read about the selection, and it didn't occur to me this was the reason. Indeed, there were no records within last 8 hours.

When I wrote a correct SQL query, everything worked correctly.

However, there's still the problem with error window that crashes QGIS. If I can help debugging, please guide me.

**Comment by lokeshsk** [comment]
Hi,
What's the error, is it the another issue [3](https://github.com/suhora/clickhouse_connector/issues/3) ?
If yes, we can continue discussion in that thread, and I can mark this one as closed.
